In [1]:
import requests
import json
from sqlalchemy import create_engine
import pandas as pd
from sqlalchemy.dialects.postgresql import insert

In [2]:
response_API = requests.get('https://api.punkapi.com/v2/beers?page=1&per_page=10')
#print(response_API.status_code)

In [3]:
required_cols = ['id','name','tagline','first_brewed','abv']

In [4]:
with open('json-data/data.json', 'w') as f:
    json.dump(data, f)

FileNotFoundError: [Errno 2] No such file or directory: 'json-data/data.json'

In [5]:
engine = create_engine('postgresql://postgres:delete@localhost:5432/airup')

In [6]:
data = json.loads(response_API.text)
data

[{'id': 1,
  'name': 'Buzz',
  'tagline': 'A Real Bitter Experience.',
  'first_brewed': '09/2007',
  'description': 'A light, crisp and bitter IPA brewed with English and American hops. A small batch brewed only once.',
  'image_url': 'https://images.punkapi.com/v2/keg.png',
  'abv': 4.5,
  'ibu': 60,
  'target_fg': 1010,
  'target_og': 1044,
  'ebc': 20,
  'srm': 10,
  'ph': 4.4,
  'attenuation_level': 75,
  'volume': {'value': 20, 'unit': 'litres'},
  'boil_volume': {'value': 25, 'unit': 'litres'},
  'method': {'mash_temp': [{'temp': {'value': 64, 'unit': 'celsius'},
     'duration': 75}],
   'fermentation': {'temp': {'value': 19, 'unit': 'celsius'}},
   'twist': None},
  'ingredients': {'malt': [{'name': 'Maris Otter Extra Pale',
     'amount': {'value': 3.3, 'unit': 'kilograms'}},
    {'name': 'Caramalt', 'amount': {'value': 0.2, 'unit': 'kilograms'}},
    {'name': 'Munich', 'amount': {'value': 0.4, 'unit': 'kilograms'}}],
   'hops': [{'name': 'Fuggles',
     'amount': {'value': 25, 'unit': 'grams'},
     'add': 'start',
     'attribute': 'bitter'},
    {'name': 'First Gold',
     'amount': {'value': 25, 'unit': 'grams'},
     'add': 'start',
     'attribute': 'bitter'},
    {'name': 'Fuggles',
     'amount': {'value': 37.5, 'unit': 'grams'},
     'add': 'middle',
     'attribute': 'flavour'},
    {'name': 'First Gold',
     'amount': {'value': 37.5, 'unit': 'grams'},
     'add': 'middle',
     'attribute': 'flavour'},
    {'name': 'Cascade',
     'amount': {'value': 37.5, 'unit': 'grams'},
     'add': 'end',
     'attribute': 'flavour'}],
   'yeast': 'Wyeast 1056 - American Ale™'},
  'food_pairing': ['Spicy chicken tikka masala',
   'Grilled chicken quesadilla',
   'Caramel toffee cake'],
  'brewers_tips': 'The earthy and floral aromas from the hops can be overpowering. Drop a little Cascade in at the end of the boil to lift the profile with a bit of citrus.',
  'contributed_by': 'Sam Mason <samjbmason>'},
 {'id': 2,
  'name': 'Trashy Blonde',
  'tagline': "You Know You Shouldn't",
  'first_brewed': '04/2008',
  'description': 'A titillating, neurotic, peroxide punk of a Pale Ale. Combining attitude, style, substance, and a little bit of low self esteem for good measure; what would your mother say? The seductive lure of the sassy passion fruit hop proves too much to resist. All that is even before we get onto the fact that there are no additives, preservatives, pasteurization or strings attached. All wrapped up with the customary BrewDog bite and imaginative twist.',
  'image_url': 'https://images.punkapi.com/v2/2.png',
  'abv': 4.1,
  'ibu': 41.5,
  'target_fg': 1010,
  'target_og': 1041.7,
  'ebc': 15,
  'srm': 15,
  'ph': 4.4,
  'attenuation_level': 76,
  'volume': {'value': 20, 'unit': 'litres'},
  'boil_volume': {'value': 25, 'unit': 'litres'},
  'method': {'mash_temp': [{'temp': {'value': 69, 'unit': 'celsius'},
     'duration': None}],
   'fermentation': {'temp': {'value': 18, 'unit': 'celsius'}},
   'twist': None},
  'ingredients': {'malt': [{'name': 'Maris Otter Extra Pale',
     'amount': {'value': 3.25, 'unit': 'kilograms'}},
    {'name': 'Caramalt', 'amount': {'value': 0.2, 'unit': 'kilograms'}},
    {'name': 'Munich', 'amount': {'value': 0.4, 'unit': 'kilograms'}}],
   'hops': [{'name': 'Amarillo',
     'amount': {'value': 13.8, 'unit': 'grams'},
     'add': 'start',
     'attribute': 'bitter'},
    {'name': 'Simcoe',
     'amount': {'value': 13.8, 'unit': 'grams'},
     'add': 'start',
     'attribute': 'bitter'},
    {'name': 'Amarillo',
     'amount': {'value': 26.3, 'unit': 'grams'},
     'add': 'end',
     'attribute': 'flavour'},
    {'name': 'Motueka',
     'amount': {'value': 18.8, 'unit': 'grams'},
     'add': 'end',
     'attribute': 'flavour'}],
   'yeast': 'Wyeast 1056 - American Ale™'},
  'food_pairing': ['Fresh crab with lemon',
   'Garlic butter dipping sauce',
   'Goats cheese salad',
   'Creamy lemon bar doused in powdered sugar'],
  'brewers_tips': 'Be careful not to collect too much wort from the mash. Once the sugars are all washed out there are some very unpleasant grainy tasting compounds that can be extracted into the wort.',
  'contributed_by': 'Sam Mason <samjbmason>'},
 {'id': 3,
  'name': 'Berliner Weisse With Yuzu - B-Sides',
  'tagline': 'Japanese Citrus Berliner Weisse.',
  'first_brewed': '11/2015',
  'description': 'Japanese citrus fruit intensifies the sour nature of this German classic.',
  'image_url': 'https://images.punkapi.com/v2/keg.png',
  'abv': 4.2,
  'ibu': 8,
  'target_fg': 1007,
  'target_og': 1040,
  'ebc': 8,
  'srm': 4,
  'ph': 3.2,
  'attenuation_level': 83,
  'volume': {'value': 20, 'unit': 'litres'},
  'boil_volume': {'value': 25, 'unit': 'litres'},
  'method': {'mash_temp': [{'temp': {'value': 60, 'unit': 'celsius'},
     'duration': 10},
    {'temp': {'value': 65, 'unit': 'celsius'}, 'duration': 30},
    {'temp': {'value': 72, 'unit': 'celsius'}, 'duration': 10},
    {'temp': {'value': 78, 'unit': 'celsius'}, 'duration': 5}],
   'fermentation': {'temp': {'value': 21, 'unit': 'celsius'}},
   'twist': 'Soured naturally using the kettle souring technique, Yuzu fruit: 50g at middle, Yuzu juice: 200ml at FV'},
  'ingredients': {'malt': [{'name': 'Propino Pale Malt',
     'amount': {'value': 1.63, 'unit': 'kilograms'}},
    {'name': 'Wheat Malt', 'amount': {'value': 1.63, 'unit': 'kilograms'}},
    {'name': 'Propino Pale Malt for kettle souring',
     'amount': {'value': 0.03, 'unit': 'kilograms'}},
    {'name': 'Acidulated Malt for kettle souring',
     'amount': {'value': 0.03, 'unit': 'kilograms'}}],
   'hops': [{'name': 'Bramling Cross',
     'amount': {'value': 10, 'unit': 'grams'},
     'add': 'middle',
     'attribute': 'bitter'}],
   'yeast': 'Wyeast 1056 - American Ale™'},
  'food_pairing': ['Smoked chicken wings', 'Miso ramen', 'Yuzu cheesecake'],
  'brewers_tips': 'Clean everything twice. All you want is the clean sourness of lactobacillus.',
  'contributed_by': 'Sam Mason <samjbmason>'},
 {'id': 4,
  'name': 'Pilsen Lager',
  'tagline': 'Unleash the Yeast Series.',
  'first_brewed': '09/2013',
  'description': 'Our Unleash the Yeast series was an epic experiment into the differences in aroma and flavour provided by switching up your yeast. We brewed up a wort with a light caramel note and some toasty biscuit flavour, and hopped it with Amarillo and Centennial for a citrusy bitterness. Everything else is down to the yeast. Pilsner yeast ferments with no fruity esters or spicy phenols, although it can add a hint of butterscotch.',
  'image_url': 'https://images.punkapi.com/v2/4.png',
  'abv': 6.3,
  'ibu': 55,
  'target_fg': 1012,
  'target_og': 1060,
  'ebc': 30,
  'srm': 15,
  'ph': 4.4,
  'attenuation_level': 80,
  'volume': {'value': 20, 'unit': 'litres'},
  'boil_volume': {'value': 25, 'unit': 'litres'},
  'method': {'mash_temp': [{'temp': {'value': 65, 'unit': 'celsius'},
     'duration': None}],
   'fermentation': {'temp': {'value': 9, 'unit': 'celsius'}},
   'twist': None},
  'ingredients': {'malt': [{'name': 'Extra Pale',
     'amount': {'value': 4.58, 'unit': 'kilograms'}},
    {'name': 'Caramalt', 'amount': {'value': 0.25, 'unit': 'kilograms'}},
    {'name': 'Dark Crystal', 'amount': {'value': 0.06, 'unit': 'kilograms'}},
    {'name': 'Munich', 'amount': {'value': 0.25, 'unit': 'kilograms'}}],
   'hops': [{'name': 'Centennial',
     'amount': {'value': 5, 'unit': 'grams'},
     'add': 'start',
     'attribute': 'bitter'},
    {'name': 'Amarillo',
     'amount': {'value': 5, 'unit': 'grams'},
     'add': 'start',
     'attribute': 'bitter'},
    {'name': 'Centennial',
     'amount': {'value': 10, 'unit': 'grams'},
     'add': 'middle',
     'attribute': 'flavour'},
    {'name': 'Amarillo',
     'amount': {'value': 10, 'unit': 'grams'},
     'add': 'middle',
     'attribute': 'flavour'},
    {'name': 'Centennial',
     'amount': {'value': 17.5, 'unit': 'grams'},
     'add': 'end',
     'attribute': 'flavour'},
    {'name': 'Amarillo',
     'amount': {'value': 17.5, 'unit': 'grams'},
     'add': 'end',
     'attribute': 'flavour'}],
   'yeast': 'Wyeast 2007 - Pilsen Lager™'},
  'food_pairing': ['Spicy crab cakes',
   'Spicy cucumber and carrot Thai salad',
   'Sweet filled dumplings'],
  'brewers_tips': 'Play around with the fermentation temperature to get the best flavour profile from the individual yeasts.',
  'contributed_by': 'Ali Skinner <AliSkinner>'},
 {'id': 5,
  'name': 'Avery Brown Dredge',
  'tagline': "Bloggers' Imperial Pilsner.",
  'first_brewed': '02/2011',
  'description': 'An Imperial Pilsner in collaboration with beer writers. Tradition. Homage. Revolution. We wanted to showcase the awesome backbone of the Czech brewing tradition, the noble Saaz hop, and also tip our hats to the modern beers that rock our world, and the people who make them.',
  'image_url': 'https://images.punkapi.com/v2/5.png',
  'abv': 7.2,
  'ibu': 59,
  'target_fg': 1027,
  'target_og': 1069,
  'ebc': 10,
  'srm': 5,
  'ph': 4.4,
  'attenuation_level': 67,
  'volume': {'value': 20, 'unit': 'litres'},
  'boil_volume': {'value': 25, 'unit': 'litres'},
  'method': {'mash_temp': [{'temp': {'value': 66, 'unit': 'celsius'},
     'duration': 70}],
   'fermentation': {'temp': {'value': 10, 'unit': 'celsius'}},
   'twist': None},
  'ingredients': {'malt': [{'name': 'Lager Malt',
     'amount': {'value': 6.63, 'unit': 'kilograms'}},
    {'name': 'Wheat', 'amount': {'value': 0.38, 'unit': 'kilograms'}}],
   'hops': [{'name': 'Saaz',
     'amount': {'value': 60, 'unit': 'grams'},
     'add': 'start',
     'attribute': 'bitter'},
    {'name': 'Saaz',
     'amount': {'value': 60, 'unit': 'grams'},
     'add': 'middle',
     'attribute': 'flavour'},
    {'name': 'Saaz',
     'amount': {'value': 60, 'unit': 'grams'},
     'add': 'end',
     'attribute': 'flavour'}],
   'yeast': 'Wyeast 2007 - Pilsen Lager™'},
  'food_pairing': ['Vietnamese squid salad',
   'Chargrilled corn on the cob with paprika butter',
   'Strawberry and rhubarb pie'],
  'brewers_tips': 'Make sure you have a big enough yeast starter to ferment through the OG and lager successfully.',
  'contributed_by': 'Sam Mason <samjbmason>'},
 {'id': 6,
  'name': 'Electric India',
  'tagline': 'Vibrant Hoppy Saison.',
  'first_brewed': '05/2013',
  'description': 'Re-brewed as a spring seasonal, this beer – which appeared originally as an Equity Punk shareholder creation – retains its trademark spicy, fruity edge. A perfect blend of Belgian Saison and US IPA, crushed peppercorns and heather honey are also added to produce a genuinely unique beer.',
  'image_url': 'https://images.punkapi.com/v2/6.png',
  'abv': 5.2,
  'ibu': 38,
  'target_fg': 1005,
  'target_og': 1045,
  'ebc': 15,
  'srm': 7.5,
  'ph': 4.4,
  'attenuation_level': 88.9,
  'volume': {'value': 20, 'unit': 'litres'},
  'boil_volume': {'value': 25, 'unit': 'litres'},
  'method': {'mash_temp': [{'temp': {'value': 65, 'unit': 'celsius'},
     'duration': 75}],
   'fermentation': {'temp': {'value': 22, 'unit': 'celsius'}},
   'twist': 'Honey: 62.5g at End (WP), Coriander Seeds: 8.5g at 45mins'},
  'ingredients': {'malt': [{'name': 'Extra Pale',
     'amount': {'value': 3.63, 'unit': 'kilograms'}},
    {'name': 'Munich', 'amount': {'value': 0.13, 'unit': 'kilograms'}},
    {'name': 'Wheat', 'amount': {'value': 0.25, 'unit': 'kilograms'}}],
   'hops': [{'name': 'Amarillo',
     'amount': {'value': 2.5, 'unit': 'grams'},
     'add': 'start',
     'attribute': 'bitter'},
    {'name': 'Nelson Sauvin',
     'amount': {'value': 5, 'unit': 'grams'},
     'add': 'middle',
     'attribute': 'flavour'},
    {'name': 'Amarillo',
     'amount': {'value': 5, 'unit': 'grams'},
     'add': 'middle',
     'attribute': 'flavour'},
    {'name': 'Peppercorns',
     'amount': {'value': 2.5, 'unit': 'grams'},
     'add': 'middle',
     'attribute': 'flavour'},
    {'name': 'Nelson Sauvin',
     'amount': {'value': 20, 'unit': 'grams'},
     'add': 'end',
     'attribute': 'flavour'},
    {'name': 'Amarillo',
     'amount': {'value': 12.5, 'unit': 'grams'},
     'add': 'end',
     'attribute': 'flavour'}],
   'yeast': 'Wyeast 3711 - French Saison™'},
  'food_pairing': ['Mussels with a garlic and herb sauce',
   'Crab melt sandwich',
   'Shortbread cookies'],
  'brewers_tips': 'Source some really good heather honey to get the right spicy esters in the beer.',
  'contributed_by': 'Sam Mason <samjbmason>'},
 {'id': 7,
  'name': 'AB:12',
  'tagline': 'Imperial Black Belgian Ale.',
  'first_brewed': '07/2012',
  'description': 'An Imperial Black Belgian Ale aged in old Invergordon Scotch whisky barrels with mountains of raspberries, tayberries and blackberries in each cask. Decadent but light and dry, this beer would make a fantastic base for ageing on pretty much any dark fruit - we used raspberries, tayberries and blackberries beause they were local.',
  'image_url': 'https://images.punkapi.com/v2/7.png',
  'abv': 11.2,
  'ibu': 35,
  'target_fg': 1017,
  'target_og': 1108,
  'ebc': 80,
  'srm': 40,
  'ph': 5.3,
  'attenuation_level': 84,
  'volume': {'value': 20, 'unit': 'litres'},
  'boil_volume': {'value': 25, 'unit': 'litres'},
  'method': {'mash_temp': [{'temp': {'value': 69, 'unit': 'celsius'},
     'duration': 105}],
   'fermentation': {'temp': {'value': 21, 'unit': 'celsius'}},
   'twist': 'Aged in whisky barrels with raspberries, tayberries and blackberries'},
  'ingredients': {'malt': [{'name': 'Extra Pale',
     'amount': {'value': 9.69, 'unit': 'kilograms'}},
    {'name': 'Chocolate', 'amount': {'value': 0.19, 'unit': 'kilograms'}},
    {'name': 'Carafa Special Malt Type 3',
     'amount': {'value': 0.44, 'unit': 'kilograms'}}],
   'hops': [{'name': 'Tomahawk',
     'amount': {'value': 31.25, 'unit': 'grams'},
     'add': 'start',
     'attribute': 'bitter'},
    {'name': 'Magnum',
     'amount': {'value': 12.5, 'unit': 'grams'},
     'add': 'start',
     'attribute': 'bitter'},
    {'name': 'Magnum',
     'amount': {'value': 12.5, 'unit': 'grams'},
     'add': 'middle',
     'attribute': 'flavour'},
    {'name': 'Tomahawk',
     'amount': {'value': 12.5, 'unit': 'grams'},
     'add': 'end',
     'attribute': 'flavour'},
    {'name': 'Centennial',
     'amount': {'value': 25, 'unit': 'grams'},
     'add': 'end',
     'attribute': 'flavour'},
    {'name': 'Amarillo',
     'amount': {'value': 25, 'unit': 'grams'},
     'add': 'end',
     'attribute': 'flavour'},
    {'name': 'Centennial',
     'amount': {'value': 25, 'unit': 'grams'},
     'add': 'dry hop',
     'attribute': 'aroma'},
    {'name': 'Amarillo',
     'amount': {'value': 25, 'unit': 'grams'},
     'add': 'dry hop',
     'attribute': 'aroma'},
    {'name': 'Tomahawk',
     'amount': {'value': 37.5, 'unit': 'grams'},
     'add': 'dry hop',
     'attribute': 'aroma'}],
   'yeast': 'Wyeast 3522 - Belgian Ardennes™'},
  'food_pairing': ['Tandoori lamb with pomegranate',
   'Beef Wellington with a red wine jus',
   'Raspberry chocolate torte'],
  'brewers_tips': "Don't worry too much about controlling the temperature with the Belgian yeast strain - just make sure it doesn't rise above 30°C!",
  'contributed_by': 'Sam Mason <samjbmason>'},
 {'id': 8,
  'name': 'Fake Lager',
  'tagline': 'Bohemian Pilsner.',
  'first_brewed': '03/2013',
  'description': 'Fake is the new black. Fake is where it is at. Fake Art, fake brands, fake breasts, and fake lager. We want to play our part in the ugly fallout from the Lager Dream. Say hello to Fake Lager – a zesty, floral 21st century faux masterpiece with added BrewDog bitterness.',
  'image_url': 'https://images.punkapi.com/v2/8.png',
  'abv': 4.7,
  'ibu': 40,
  'target_fg': 1010,
  'target_og': 1046,
  'ebc': 12,
  'srm': 6,
  'ph': 4.4,
  'attenuation_level': 78,
  'volume': {'value': 20, 'unit': 'litres'},
  'boil_volume': {'value': 25, 'unit': 'litres'},
  'method': {'mash_temp': [{'temp': {'value': 65, 'unit': 'celsius'},
     'duration': 75}],
   'fermentation': {'temp': {'value': 10, 'unit': 'celsius'}},
   'twist': None},
  'ingredients': {'malt': [{'name': 'Extra Pale',
     'amount': {'value': 3.33, 'unit': 'kilograms'}},
    {'name': 'Munich', 'amount': {'value': 0.42, 'unit': 'kilograms'}},
    {'name': 'Caramalt', 'amount': {'value': 0.28, 'unit': 'kilograms'}},
    {'name': 'Acidulated Malt',
     'amount': {'value': 0.07, 'unit': 'kilograms'}}],
   'hops': [{'name': 'Magnum',
     'amount': {'value': 7.5, 'unit': 'grams'},
     'add': 'start',
     'attribute': 'bitter'},
    {'name': 'Magnum',
     'amount': {'value': 5, 'unit': 'grams'},
     'add': 'middle',
     'attribute': 'flavour'},
    {'name': 'Hersbrucker',
     'amount': {'value': 6.25, 'unit': 'grams'},
     'add': 'middle',
     'attribute': 'flavour'},
    {'name': 'Saaz',
     'amount': {'value': 6.25, 'unit': 'grams'},
     'add': 'middle',
     'attribute': 'flavour'},
    {'name': 'Hersbrucker',
     'amount': {'value': 18.75, 'unit': 'grams'},
     'add': 'end',
     'attribute': 'flavour'},
    {'name': 'Saaz',
     'amount': {'value': 18.75, 'unit': 'grams'},
     'add': 'end',
     'attribute': 'flavour'}],
   'yeast': 'Wyeast 2007 - Pilsen Lager™'},
  'food_pairing': ['Fried crab cakes with avocado salsa',
   'Spicy shredded pork roll with hot dipping sauce',
   'Key lime pie'],
  'brewers_tips': "Once the primary fermentation is complete get this beer as cold as you can and let it mature for as long as you've got.",
  'contributed_by': 'Sam Mason <samjbmason>'},
 {'id': 9,
  'name': 'AB:07',
  'tagline': 'Whisky Cask-Aged Scotch Ale.',
  'first_brewed': '03/2010',
  'description': 'Whisky cask-aged imperial scotch ale. Beer perfect for when the rain is coming sideways. Liquorice, plum and raisin temper the warming alcohol, producing a beer capable of holding back the Scottish chill.',
  'image_url': 'https://images.punkapi.com/v2/9.png',
  'abv': 12.5,
  'ibu': 30,
  'target_fg': 1020,
  'target_og': 1106,
  'ebc': 84,
  'srm': 42,
  'ph': 5.6,
  'attenuation_level': 83,
  'volume': {'value': 20, 'unit': 'litres'},
  'boil_volume': {'value': 25, 'unit': 'litres'},
  'method': {'mash_temp': [{'temp': {'value': 65, 'unit': 'celsius'},
     'duration': 105}],
   'fermentation': {'temp': {'value': 11, 'unit': 'celsius'}},
   'twist': 'Scottish Heather Honey: 62.5g at middle, Add honey during the boil. After fermentation, age in a Scottish whisky cask'},
  'ingredients': {'malt': [{'name': 'Munich',
     'amount': {'value': 5.63, 'unit': 'kilograms'}},
    {'name': 'Flaked Oats', 'amount': {'value': 1.88, 'unit': 'kilograms'}},
    {'name': 'Wheat', 'amount': {'value': 1.88, 'unit': 'kilograms'}},
    {'name': 'Caramalt', 'amount': {'value': 1.25, 'unit': 'kilograms'}},
    {'name': 'Crystal', 'amount': {'value': 0.63, 'unit': 'kilograms'}},
    {'name': 'Dark Crystal', 'amount': {'value': 0.63, 'unit': 'kilograms'}},
    {'name': 'Chocolate', 'amount': {'value': 0.31, 'unit': 'kilograms'}},
    {'name': 'Peated Malt', 'amount': {'value': 0.13, 'unit': 'kilograms'}},
    {'name': 'Amber', 'amount': {'value': 0.13, 'unit': 'kilograms'}},
    {'name': 'Brown', 'amount': {'value': 0.13, 'unit': 'kilograms'}}],
   'hops': [{'name': 'Saaz',
     'amount': {'value': 25, 'unit': 'grams'},
     'add': 'start',
     'attribute': 'bitter'},
    {'name': 'First Gold',
     'amount': {'value': 31.3, 'unit': 'grams'},
     'add': 'start',
     'attribute': 'bitter'}],
   'yeast': 'Saflager S189'},
  'food_pairing': ['Kedgeree',
   'Scotch broth with sourdough bread',
   'Clootie dumpling'],
  'brewers_tips': 'Authentic heather honey adds a beautiful floral top note that is unachievable any other way.',
  'contributed_by': 'Sam Mason <samjbmason>'},
 {'id': 10,
  'name': 'Bramling X',
  'tagline': 'Single Hop IPA Series - 2011.',
  'first_brewed': '01/2011',

In [7]:
df = pd.json_normalize(data)
# df = df[required_cols]
df

,id,name,tagline,first_brewed,description,image_url,abv,ibu,target_fg,target_og,...,volume.unit,boil_volume.value,boil_volume.unit,method.mash_temp,method.fermentation.temp.value,method.fermentation.temp.unit,method.twist,ingredients.malt,ingredients.hops,ingredients.yeast
0,1,Buzz,A Real Bitter Experience.,09/2007,"A light, crisp and bitter IPA brewed with Engl...",https://images.punkapi.com/v2/keg.png,4.5,60.0,1010,1044.0,...,litres,25,litres,"[{'temp': {'value': 64, 'unit': 'celsius'}, 'd...",19,celsius,None,"[{'name': 'Maris Otter Extra Pale', 'amount': ...","[{'name': 'Fuggles', 'amount': {'value': 25, '...",Wyeast 1056 - American Ale™
1,2,Trashy Blonde,You Know You Shouldn't,04/2008,"A titillating, neurotic, peroxide punk of a Pa...",https://images.punkapi.com/v2/2.png,4.1,41.5,1010,1041.7,...,litres,25,litres,"[{'temp': {'value': 69, 'unit': 'celsius'}, 'd...",18,celsius,None,"[{'name': 'Maris Otter Extra Pale', 'amount': ...","[{'name': 'Amarillo', 'amount': {'value': 13.8...",Wyeast 1056 - American Ale™
2,3,Berliner Weisse With Yuzu - B-Sides,Japanese Citrus Berliner Weisse.,11/2015,Japanese citrus fruit intensifies the sour nat...,https://images.punkapi.com/v2/keg.png,4.2,8.0,1007,1040.0,...,litres,25,litres,"[{'temp': {'value': 60, 'unit': 'celsius'}, 'd...",21,celsius,Soured naturally using the kettle souring tech...,"[{'name': 'Propino Pale Malt', 'amount': {'val...","[{'name': 'Bramling Cross', 'amount': {'value'...",Wyeast 1056 - American Ale™
3,4,Pilsen Lager,Unleash the Yeast Series.,09/2013,Our Unleash the Yeast series was an epic exper...,https://images.punkapi.com/v2/4.png,6.3,55.0,1012,1060.0,...,litres,25,litres,"[{'temp': {'value': 65, 'unit': 'celsius'}, 'd...",9,celsius,None,"[{'name': 'Extra Pale', 'amount': {'value': 4....","[{'name': 'Centennial', 'amount': {'value': 5,...",Wyeast 2007 - Pilsen Lager™
4,5,Avery Brown Dredge,Bloggers' Imperial Pilsner.,02/2011,An Imperial Pilsner in collaboration with beer...,https://images.punkapi.com/v2/5.png,7.2,59.0,1027,1069.0,...,litres,25,litres,"[{'temp': {'value': 66, 'unit': 'celsius'}, 'd...",10,celsius,None,"[{'name': 'Lager Malt', 'amount': {'value': 6....","[{'name': 'Saaz', 'amount': {'value': 60, 'uni...",Wyeast 2007 - Pilsen Lager™
5,6,Electric India,Vibrant Hoppy Saison.,05/2013,"Re-brewed as a spring seasonal, this beer – wh...",https://images.punkapi.com/v2/6.png,5.2,38.0,1005,1045.0,...,litres,25,litres,"[{'temp': {'value': 65, 'unit': 'celsius'}, 'd...",22,celsius,"Honey: 62.5g at End (WP), Coriander Seeds: 8.5...","[{'name': 'Extra Pale', 'amount': {'value': 3....","[{'name': 'Amarillo', 'amount': {'value': 2.5,...",Wyeast 3711 - French Saison™
6,7,AB:12,Imperial Black Belgian Ale.,07/2012,An Imperial Black Belgian Ale aged in old Inve...,https://images.punkapi.com/v2/7.png,11.2,35.0,1017,1108.0,...,litres,25,litres,"[{'temp': {'value': 69, 'unit': 'celsius'}, 'd...",21,celsius,"Aged in whisky barrels with raspberries, taybe...","[{'name': 'Extra Pale', 'amount': {'value': 9....","[{'name': 'Tomahawk', 'amount': {'value': 31.2...",Wyeast 3522 - Belgian Ardennes™
7,8,Fake Lager,Bohemian Pilsner.,03/2013,Fake is the new black. Fake is where it is at....,https://images.punkapi.com/v2/8.png,4.7,40.0,1010,1046.0,...,litres,25,litres,"[{'temp': {'value': 65, 'unit': 'celsius'}, 'd...",10,celsius,None,"[{'name': 'Extra Pale', 'amount': {'value': 3....","[{'name': 'Magnum', 'amount': {'value': 7.5, '...",Wyeast 2007 - Pilsen Lager™
8,9,AB:07,Whisky Cask-Aged Scotch Ale.,03/2010,Whisky cask-aged imperial scotch ale. Beer per...,https://images.punkapi.com/v2/9.png,12.5,30.0,1020,1106.0,...,litres,25,litres,"[{'temp': {'value': 65, 'unit': 'celsius'}, 'd...",11,celsius,"Scottish Heather Honey: 62.5g at middle, Add h...","[{'name': 'Munich', 'amount': {'value': 5.63, ...","[{'name': 'Saaz', 'amount': {'value': 25, 'uni...",Saflager S189
9,10,Bramling X,Single Hop IPA Series - 2011.,01/2011,"Good old Bramling Cross is elegant, refined, a...",https://images.punkapi.com/v2/10.png,7.5,75.0,1013,1068.0,...,litres,25,litres,"[{'temp': {'value': 65, 'unit': 'celsius'}, 'd...",19,celsius,None,"[{'name': 'Extra Pale', 'amount': {'value': 6....","[{'name': 'Bramling Cross', 'amount': {'value'...",Wyeast 1056 - American Ale™

In [126]:
def insert_on_duplicate(table, conn, keys, data_iter):
    insert_stmt = insert(table.table).values(list(data_iter))
    do_nothing_stmt = insert_stmt.on_conflict_do_nothing(index_elements=['id'])
    conn.execute(do_nothing_stmt)

In [137]:
from sqlalchemy import types

data_type = {'id': types.Integer, 'name': types.String, 'tagline': types.String, 'first_brewed': types.String(50),
                 'abv': types.Float}

In [138]:
df.to_sql('beers1', engine, if_exists='replace', index=False, dtype=data_type)

In [141]:
df['id'].max()

40

In [198]:
df[['id','name','tagline','first_brewed','abv']]

,id,name,tagline,first_brewed,abv
0,1,Buzz,A Real Bitter Experience.,09/2007,4.5
1,2,Trashy Blonde,You Know You Shouldn't,04/2008,4.1
2,3,Berliner Weisse With Yuzu - B-Sides,Japanese Citrus Berliner Weisse.,11/2015,4.2
3,4,Pilsen Lager,Unleash the Yeast Series.,09/2013,6.3
4,5,Avery Brown Dredge,Bloggers' Imperial Pilsner.,02/2011,7.2
5,6,Electric India,Vibrant Hoppy Saison.,05/2013,5.2
6,7,AB:12,Imperial Black Belgian Ale.,07/2012,11.2
7,8,Fake Lager,Bohemian Pilsner.,03/2013,4.7
8,9,AB:07,Whisky Cask-Aged Scotch Ale.,03/2010,12.5
9,10,Bramling X,Single Hop IPA Series - 2011.,01/2011,7.5

In [195]:
df_malt = pd.json_normalize(data[0]['ingredients']['malt'])
df_malt['ingredients_id'] = 1
df_malt

                     name  amount.value amount.unit  ingredients_id
0  Maris Otter Extra Pale           3.3   kilograms               1
1                Caramalt           0.2   kilograms               1
2                  Munich           0.4   kilograms               1

In [196]:
df_hops = pd.json_normalize(data[0]['ingredients']['hops'])
df_hops['ingredients_id'] = 1
df_hops

         name     add attribute  amount.value amount.unit  ingredients_id
0     Fuggles   start    bitter          25.0       grams               1
1  First Gold   start    bitter          25.0       grams               1
2     Fuggles  middle   flavour          37.5       grams               1
3  First Gold  middle   flavour          37.5       grams               1
4     Cascade     end   flavour          37.5       grams               1

Normalization

In [219]:
df_nz = df[['id','name','tagline','first_brewed','abv', 'ingredients.yeast', 'ingredients.malt']]
df_nz = df_nz.rename(columns = {"ingredients.yeast": "yeast"})
df_nz

,id,name,tagline,first_brewed,abv,yeast,ingredients.malt
0,1,Buzz,A Real Bitter Experience.,09/2007,4.5,Wyeast 1056 - American Ale™,"[{'name': 'Maris Otter Extra Pale', 'amount': ..."
1,2,Trashy Blonde,You Know You Shouldn't,04/2008,4.1,Wyeast 1056 - American Ale™,"[{'name': 'Maris Otter Extra Pale', 'amount': ..."
2,3,Berliner Weisse With Yuzu - B-Sides,Japanese Citrus Berliner Weisse.,11/2015,4.2,Wyeast 1056 - American Ale™,"[{'name': 'Propino Pale Malt', 'amount': {'val..."
3,4,Pilsen Lager,Unleash the Yeast Series.,09/2013,6.3,Wyeast 2007 - Pilsen Lager™,"[{'name': 'Extra Pale', 'amount': {'value': 4...."
4,5,Avery Brown Dredge,Bloggers' Imperial Pilsner.,02/2011,7.2,Wyeast 2007 - Pilsen Lager™,"[{'name': 'Lager Malt', 'amount': {'value': 6...."
5,6,Electric India,Vibrant Hoppy Saison.,05/2013,5.2,Wyeast 3711 - French Saison™,"[{'name': 'Extra Pale', 'amount': {'value': 3...."
6,7,AB:12,Imperial Black Belgian Ale.,07/2012,11.2,Wyeast 3522 - Belgian Ardennes™,"[{'name': 'Extra Pale', 'amount': {'value': 9...."
7,8,Fake Lager,Bohemian Pilsner.,03/2013,4.7,Wyeast 2007 - Pilsen Lager™,"[{'name': 'Extra Pale', 'amount': {'value': 3...."
8,9,AB:07,Whisky Cask-Aged Scotch Ale.,03/2010,12.5,Saflager S189,"[{'name': 'Munich', 'amount': {'value': 5.63, ..."
9,10,Bramling X,Single Hop IPA Series - 2011.,01/2011,7.5,Wyeast 1056 - American Ale™,"[{'name': 'Extra Pale', 'amount': {'value': 6...."

In [207]:
df_malt = pd.json_normalize(data[0]['ingredients']['malt'])
df_malt['beer_id'] = 1
df_malt = df_malt.rename(columns = {"amount.value": "amount_value", "amount.unit":"amount_unit"})
df_malt

                     name  amount_value amount_unit  beer_id
0  Maris Otter Extra Pale           3.3   kilograms        1
1                Caramalt           0.2   kilograms        1
2                  Munich           0.4   kilograms        1

In [9]:
data[0]['ingredients']['malt']

[{'name': 'Maris Otter Extra Pale',
  'amount': {'value': 3.3, 'unit': 'kilograms'}},
 {'name': 'Caramalt', 'amount': {'value': 0.2, 'unit': 'kilograms'}},
 {'name': 'Munich', 'amount': {'value': 0.4, 'unit': 'kilograms'}}]

In [206]:
df_hops = pd.json_normalize(data[0]['ingredients']['hops'])
df_hops['beer_id'] = 1
df_hops = df_hops.rename(columns = {"amount.value": "amount_value", "amount.unit":"amount_unit"})
df_hops

         name     add attribute  amount_value amount_unit  beer_id
0     Fuggles   start    bitter          25.0       grams        1
1  First Gold   start    bitter          25.0       grams        1
2     Fuggles  middle   flavour          37.5       grams        1
3  First Gold  middle   flavour          37.5       grams        1
4     Cascade     end   flavour          37.5       grams        1

In [218]:
for i, row in df_hops.iterrows():
    print(i, row['name'])

0 Fuggles
1 First Gold
2 Fuggles
3 First Gold
4 Cascade

# food pairning

In [229]:

ls = data[0]['food_pairing']

In [231]:
ls.append("dsds'ds")

In [242]:
import re
[re.sub('[^a-zA-Z0-9 ]+', '', f) for f in ls]

['Spicy chicken tikka masala',
 'Grilled chicken quesadilla',
 'Caramel toffee cake',
 'dsdsds']

In [234]:
# df['food_pairing']
df_fp = pd.DataFrame(ls, columns =['name'])
df_fp

                         name
0  Spicy chicken tikka masala
1  Grilled chicken quesadilla
2         Caramel toffee cake
3                     dsds'ds

In [235]:
df_fp['name'].astype(str).str.replace(r'[^0-9a-zA-Z ]+', '')

/tmp/ipykernel_2096910/1151582276.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df_fp['name'].astype(str).str.replace(r'[^0-9a-zA-Z ]+', '')

0    Spicy chicken tikka masala
1    Grilled chicken quesadilla
2           Caramel toffee cake
3                        dsdsds
Name: name, dtype: object